[options]
proxy_mode = False
without_demo = False
list_db = True
http_interface = 0.0.0.0
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons, /mnt/custom-addons
logfile = /var/lib/odoo/odoo.log
log_level = debug
data_dir = /var/lib/odoo
workers = 1
db_host = postgresql
db_port = 5432
db_user = odoo
db_password = password
dbfilter = ^local_odoo$
admin_passwd = $pbkdf2-sha512$600000$g9Dam/N.rzUGYGzNGcNYqw$f8W94cqQSKyrd0mEii9pPy3OT07Bm09eeNhiY14QBBvPhNw8Sn6p1GhN63N27xRTohZ68C62KjSWn9YhQzWtTQ

